apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  destination:
    namespace: flask-app
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/0xsaju/simple-webapp-mysql.git'
    targetRevision: new-ci-cd
    path: charts/flask-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
