apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/0xsaju/simple-webapp-mysql.git'
    targetRevision: new-ci-cd
    path: k3s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true