apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "AppDBPass"
        - name: MYSQL_DATABASE
          value: "webapp_mysql"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: flask-app
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
