replicaCount: 2

image:
  repository: your-docker-repository/flask-app
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: flask-app.local
      paths:
        - path: /
          pathType: Prefix
