apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: argocd
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: mysql-secret
            - configMapRef:
                name: flask-app-config
