name: CI/CD Pipeline

on:
  push:
    branches:
      - new-ci-cd
  pull_request:
    branches:
      - new-ci-cd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t 0xsaju/flask-app:${{ github.sha }} app/
        docker push 0xsaju/flask-app:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Install Helm
      uses: azure/setup-helm@v3

#    - name: Set GITHUB_TOKEN
#      env:
#        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
#      run: |
#        echo "GITHUB_TOKEN is set."

    - name: Create namespace if not exists
      run: |
        kubectl create namespace argocd || true
        kubectl create namespace flask-app || true

    - name: Helm template preview
      run: |
        helm template flask-app charts/flask-app \
          --namespace flask-app \
          --set image.repository=0xsaju/flask-app \
          --set image.tag=${{ github.sha }}

    - name: Deploy to Kubernetes with Helm
      run: |
        helm upgrade --install flask-app charts/flask-app \
          --namespace flask-app \
          --set image.repository=0xsaju/flask-app \
          --set image.tag=${{ github.sha }} \
          --wait